server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: order-book-service
        uri: lb://order-book-service
        predicates:
        - Path=/orderbook/**
        filters:
        - RewritePath=/orderbook/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: orderbook
        url: /v3/api-docs/orderbook
    
management:
  endpoints:
     web:
       exposure: 
         include: beans,env,health,info,metrics,mappings,prometheus
  endpoint:
   health:
     show-details: always
     probes:
        enabled: true