spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: qa
---
spring:
  application:
    name: discovery-service
  config:
    import: "optional:configserver:http://localhost:8088"