{
 "title": "microsercie-api-dashboard",
 "time": { "from": "2023-08-03T12:13:55.789Z", "to": "2023-08-03T12:23:55.789Z" },
 "templating": {
  "list": [
   {
    "name": "timeRate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU-Discovery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"discovery-service\"} * 100",
     "legendFormat": "Discovery-Service"
    }
   ]
  },
  {
   "title": "CPU-Config",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"config-service\"} * 100",
     "legendFormat": "config-service"
    }
   ]
  },
  {
   "title": "CPU-Gateway",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"gateway-service\"} * 100",
     "legendFormat": "gateway-service"
    }
   ]
  },
  {
   "title": "CPU-Order-Book",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"order-book-service\"} * 100",
     "legendFormat": "order-book-service"
    }
   ]
  },
  {
   "title": "GET /payment",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"payment-service\",method=\"GET\",status=\"200\",uri=\"/payment\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"payment-service\",method=\"GET\",status!=\"200\",uri=\"/payment\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "GET /gateway",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"gateway-service\",method=\"GET\",status=\"200\",uri=\"/gateway\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"gateway-service\",method=\"GET\",status!=\"200\",uri=\"/gateway\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  }
 ]
}