server:
  port: 8088
spring:
  profiles:
    active: native
    
management:
  endpoints:
     web:
       exposure: 
         include: beans,env,health,info,metrics,mappings,prometheus
  endpoint:
   health:
     show-details: always
     probes:
        enabled: true     